### ISSUE TITLE
El jugador virtual jugó de manera indefinida hasta que dio error de conexión

### ISSUE THREAD

**Issue by abdevs** [ale-bos/tsb-monopoly#4]
Logger: Creando un nuevo juego...
Logger: Dados tirados: 3 + 6 = 9
Logger: El Jugador 'auto' se movio # 1 --> # 9, NO paso por la salida
Logger: El jugador ale pagó $100
Logger: El jugador ale compró AVENIDA REINA VICTORIA
Logger: Dados tirados: 5 + 4 = 9
Logger: El Jugador 'bota' se movio # 1 --> # 10, NO paso por la salida
Logger: El jugador bota compra CALLE BRAVO MURILLO porque tiene mucho dinero.
Logger: El jugador bota pagó $120
Logger: El jugador bota pagó 120 €
Logger: El jugador bota compró CALLE BRAVO MURILLO
Logger: Dados tirados: 3 + 2 = 5
Logger: El Jugador 'bota' se movio # 10 --> # 15, NO paso por la salida
Logger: El jugador bota compra CALLE FUENCARRAL como inversión de futuro. Aun esta todo libre.
Logger: El jugador bota pagó $160
Logger: El jugador bota pagó 160 €
Logger: El jugador bota compró CALLE FUENCARRAL
Logger: Dados tirados: 4 + 1 = 5
Logger: El Jugador 'bota' se movio # 15 --> # 20, NO paso por la salida
Logger: El jugador bota compra CALLE SERRANO como inversión de futuro. Aun esta todo libre.
Logger: El jugador bota pagó $200
Logger: El jugador bota pagó 200 €
Logger: El jugador bota compró CALLE SERRANO
Logger: Dados tirados: 5 + 1 = 6
Logger: El Jugador 'bota' se movio # 20 --> # 26, NO paso por la salida
Logger: El jugador bota compra ESTACIÓN DEL MEDIODÍA como inversión de futuro. Quedan libres varias estaciones.
Logger: El jugador bota pagó $200
Logger: El jugador bota pagó 200 €
Logger: El jugador bota compró ESTACIÓN DEL MEDIODÍA
Logger: Dados tirados: 2 + 3 = 5 
Logger: El Jugador 'bota' se movio # 26 --> # 31, NO paso por la salida
Logger: El Jugador 'bota' se movio # 31 --> # 11, paso por la salida y NO cobró los $200
Logger: Dados tirados: 3 + 5 = 8
Logger: El Jugador 'bota' se movio # 11 --> # 19, NO paso por la salida
Logger: El jugador bota compra CALLE VELÁZQUEZ porque él es el único que posee propiedades en el monopolio.
Logger: El jugador bota pagó $180
Logger: El jugador bota pagó 180 €
Logger: El jugador bota compró CALLE VELÁZQUEZ
Logger: Dados tirados: 1 + 4 = 5
Logger: El Jugador 'bota' se movio # 19 --> # 24, NO paso por la salida
Logger: El jugador bota compra CALLE MARÍA DE MOLINA como inversión de futuro. Aun esta todo libre.
Logger: El jugador bota pagó $220
Logger: El jugador bota pagó 220 €
Logger: El jugador bota compró CALLE MARÍA DE MOLINA
Logger: Dados tirados: 3 + 1 = 4
Logger: El Jugador 'bota' se movio # 24 --> # 28, NO paso por la salida
Logger: El jugador bota compra CALLE BAILÉN como inversión de futuro. Aun esta todo libre.
Logger: El jugador bota pagó $260
Logger: El jugador bota pagó 260 €
Logger: El jugador bota compró CALLE BAILÉN
Logger: Dados tirados: 4 + 5 = 9
Logger: El Jugador 'bota' se movio # 28 --> # 37, NO paso por la salida
Logger: El Jugador 'bota' se movio # 37 --> # 16, paso por la salida y cobró los $200
Logger: Dados tirados: 1 + 1 = 2
Logger: El Jugador 'bota' se movio # 16 --> # 18, NO paso por la salida
Logger: El jugador bota cobró $100
Logger: Dados tirados: 5 + 4 = 9
Logger: El Jugador 'bota' se movio # 18 --> # 27, NO paso por la salida
Logger: El jugador bota no tiene dinero para comprar AVENIDA DE LOS REYES CATÓLICOS
Logger: Dados tirados: 2 + 4 = 6
Logger: El Jugador 'bota' se movio # 27 --> # 33, NO paso por la salida
Logger: El jugador bota no tiene dinero para comprar CALLE ALCALÁ
Logger: Dados tirados: 5 + 3 = 8
Logger: El Jugador 'bota' se movio # 33 --> # 1, paso por la salida y cobró los $200
Logger: Dados tirados: 6 + 4 = 10
Logger: El Jugador 'bota' se movio # 1 --> # 11, NO paso por la salida
Logger: Dados tirados: 5 + 2 = 7
Logger: El Jugador 'bota' se movio # 11 --> # 18, NO paso por la salida
Logger: El jugador bota pagó $50
Logger: El jugador bota pagó 50 €
Logger: Dados tirados: 4 + 5 = 9
Logger: El Jugador 'bota' se movio # 18 --> # 27, NO paso por la salida
Logger: El jugador bota no tiene dinero para comprar AVENIDA DE LOS REYES CATÓLICOS
Logger: Dados tirados: 1 + 3 = 4
Logger: El Jugador 'bota' se movio # 27 --> # 31, NO paso por la salida
Logger: El Jugador 'bota' se movio # 31 --> # 11, paso por la salida y NO cobró los $200
Logger: Dados tirados: 2 + 5 = 7
Logger: El Jugador 'bota' se movio # 11 --> # 18, NO paso por la salida
Logger: El Jugador 'bota' se movio # 18 --> # 2, paso por la salida y NO cobró los $200
Logger: Dados tirados: 1 + 3 = 4
Logger: El Jugador 'bota' se movio # 2 --> # 6, NO paso por la salida
Logger: El jugador bota compra ESTACIÓN DE GOYA como inversión de futuro. Quedan libres varias estaciones.
Logger: El jugador bota pagó $200
Logger: El jugador bota pagó 200 €
Logger: El jugador bota compró ESTACIÓN DE GOYA
Logger: ERROR - 
Unexpected error shuts down hub's send thread:

java.util.ConcurrentModificationException
    at java.util.ArrayList.writeObject(ArrayList.java:766)
    at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:988)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
    at java.util.ArrayList.writeObject(ArrayList.java:762)
    at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:988)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
    at monopoly.connection.GameServer$ConnectionToClient$SendThread.run(GameServer.java:558)

**Comment by alebostico** [comment]
Listo. Se cambió lo siguiente:

``` java
TableroController.actualizarEstadoJuego() {
  ...
  case ESPERANDO_TURNO:
  ...
  finalizarTurno(); //se eliminó esta linea y se pasó a realizarAccionEnCasillero()
}

TableroController.realizarAccionEnCasillero(){
  ...
  case DESCANSO:
  ...
  finalizarTurno();
  ...
}
```
